### ISSUE TITLE
Add open-source license

### ISSUE THREAD

**Issue by martinengelcke** [pclucas14/iaf-vae#1]
Hi @pclucas14 ,

Thanks a lot for re-implementing the full model in the IAF paper and creating this repo.

Would you mind adding an open-source license to the repo? I am thinking about using / improving the model for my own research and this looks like the best PyTorch implementation I have seen so far.

Best,
Martin

**Comment by pclucas14** [comment]
Hi Martin, 

thanks for your interest. I've added an MIT license to the project. 

-Lucas

**Comment by martinengelcke** [comment]
Great, thanks a lot :)
